LIBNAME=kuka
include ../../Makefile.inc
INCLUDES+= \
-I/home/youbot/youbot_driver \
-I/home/youbot/youbot_driver/soem/src
LDFLAGS+=-L/home/youbot/youbot_driver/lib
LIBOPTS+=-lYouBotDriver -lboost_date_time-mt -lboost_filesystem-mt -lboost_system-mt -lboost_thread-mt
