LIBNAME=kuka
include ../../Makefile.inc
INCLUDES+=-I/home/youbot/youbot_driver/
LDFLAGS=-L/home/youbot/youbot_driver/lib/
LIBOPTS+=-lYouBotDriver -lboost_date_time-mt -lboost_filesystem-mt -lboost_system-mt.a -lboost_thread-mt.a
