# Makefile used to build Webots files
LIBNAME?=badlibname
include ../../Makefile.inc
LUA ?= lua

all: $(LIBNAME)

# Default compiling
%.o: %.cpp
	@echo "\t" CXX $@
	@$(CXX) $(CXXFLAGS) $(INCLUDES) -o $@ -c $<
%.o: %.cc
	@echo "\t" CXX $@
	@$(CXX) $(CXXFLAGS) $(INCLUDES) -o $@ -c $<
%.o: %.c
	@echo "\t" CC $@
	@$(CC) $(CXXFLAGS) $(INCLUDES) -o $@ -c $<


$(LIBNAME): lua_$(LIBNAME).o $(EXTRA_OBJ)
	@echo "\t" LINK $@
	@$(LD) $(LDFLAGS) -o $@.$(SHLIBEXT) $^ $(LIB_DIR) $(LIBOPTS)
	@rm $^

test: $(LIBNAME)
	@test ! -f $^.so && mv $^.$(SHLIBEXT) $^.so ; echo "Testing..."
	$(LUA) test_$^.lua ; echo "done test"
	@test ! -f $^.$(SHLIBEXT) && mv $^.so $^.$(SHLIBEXT) ; echo "move back"

clean:
	rm -f *.o *.$(SHLIBEXT) *.$(MEXEXT) *.so
