LIBNAME=hokuyo
EXTRA_OBJ=CircularBuffer.o HokuyoCircular.o HokuyoCircularHardware.o
EXTRA_OBJ+=DeviceInterface.o SerialDevice.o Hokuyo.o
include ../../../Framework/Lib/Makefile.lib
LIBOPTS+=-lpthread
