#! /bin/bash

LUA=luajit
COMPUTER=`uname`
PLATFORM=vrep_ash
export THOR_HOME=$(dirname `pwd`)

if [ "$COMPUTER" = "Darwin" ]
then
  echo "On OSX!"
  eval `/usr/libexec/path_helper -s`
  source ~/.bash_profile
  
  VREP_COMMAND="/Applications/V-Rep/vrep.app/Contents/MacOS/vrep"
else
  echo "On Linux!"
  echo "Assume V-Rep installed in /usr/local/vrep"
  
  VREP_COMMAND="/usr/local/vrep/vrep"
  LD_LIBRARY_PATH="/usr/local/vrep/."
  export LD_LIBRARY_PATH
fi

if [ "$1" ]
then
  SCENE_FILE=$1
else
  SCENE_FILE="default_unreal"
fi
SCENE_FILE="$PWD/../Platform/$PLATFORM/Scenes/$SCENE_FILE.ttt"
echo "Opening $SCENE_FILE"

exec $VREP_COMMAND $SCENE_FILE &
