#! /bin/bash

#LUA=lua
LUA=luajit

COMPUTER=`uname`
if [ "$COMPUTER" = "Darwin" ]
then
  echo "On OSX!"
  eval `/usr/libexec/path_helper -s`
  source ~/.bash_profile
  
  Vrep_Home=/Applications/V-Rep/vrep.app/Contents/MacOS
  Vrep_Command="/Applications/V-Rep/vrep.app/Contents/MacOS/vrep"
else
  echo "On Linux!"
  echo "Assume V-Rep installed in /usr/local/vrep"
  
  Vrep_Home=/usr/local/vrep
  Vrep_Command="/usr/local/vrep/vrep"
fi

# Copy the controller add-on to the vrep directory
Target_File=$Vrep_Home/vrepAddOnScript_ASH.lua
echo "prefix='$(dirname `pwd`)'" > $Target_File
cat ../Platform/vrep_ash/Comms/vrep_addon.lua >> $Target_File

Scene_File="$PWD/../Platform/vrep_ash/Scenes/Ash-VREP.ttt"

exec $Vrep_Command $Scene_File &
