#! /bin/bash

LUA=luajit
COMPUTER=`uname`
PLATFORM=vrep_ash
export THOR_HOME=$(dirname `pwd`)

if [ "$COMPUTER" = "Darwin" ]
then
  echo "On OSX!"
  eval `/usr/libexec/path_helper -s`
  source ~/.bash_profile
  
  Vrep_Home=/Applications/V-Rep/vrep.app/Contents/MacOS
  Vrep_Command="/Applications/V-Rep/vrep.app/Contents/MacOS/vrep"
else
  echo "On Linux!"
  echo "Assume V-Rep installed in /usr/local/vrep"
  
  Vrep_Home=/usr/local/vrep
  Vrep_Command="/usr/local/vrep/vrep"
fi

if [ "$1" ]
then
  Scene_File=$1
else
  Scene_File="default_unreal"
fi
Scene_File="$PWD/../Platform/$PLATFORM/Scenes/$Scene_File.ttt"
echo "Opening $Scene_File"

exec $Vrep_Command $Scene_File &
