module(..., package.seeall)

-- this config file was automatically generated by the bias_editor utility

bias = {}

bias.joint_position_bias = {
  [1] = 0.000000,
}

bias.joint_position_nominal = {
  [1] = 0.000000,
}

bias.joint_force_bias = {
  [1] = 0.000000,
}

bias.joint_force_nominal = {
  [1] = 0.000000,
}

bias.motor_position_bias = {
  [1] = 0.000000,
}

bias.motor_position_nominal = {
  [1] = 0.000000,
}

bias.motor_force_bias = {
  [1] = 0.000000,
}

bias.motor_force_nominal = {
  [1] = 0.000000,
}

bias.force_torque_bias = {
  [1] = 0.000000,
  [2] = 0.000000,
  [3] = 0.000000,
  [4] = 0.000000,
  [5] = 0.000000,
  [6] = 0.000000,
  [7] = 0.000000,
  [8] = 0.000000,
  [9] = 0.000000,
  [10] = 0.000000,
  [11] = 0.000000,
  [12] = 0.000000,
}

bias.force_torque_nominal = {
  [1] = 0.000000,
  [2] = 0.000000,
  [3] = 0.000000,
  [4] = 0.000000,
  [5] = 0.000000,
  [6] = 0.000000,
  [7] = 0.000000,
  [8] = 0.000000,
  [9] = 0.000000,
  [10] = 0.000000,
  [11] = 0.000000,
  [12] = 0.000000,
}

bias.tactile_array_bias = {
  [1] = 0.000000,
  [2] = 0.000000,
  [3] = 0.000000,
  [4] = 0.000000,
  [5] = 0.000000,
  [6] = 0.000000,
}

bias.tactile_array_nominal = {
  [1] = 0.000000,
  [2] = 0.000000,
  [3] = 0.000000,
  [4] = 0.000000,
  [5] = 0.000000,
  [6] = 0.000000,
}

