# Binary dinast
all:
	c++ main.cpp dinast_grabber.cpp -L/usr/local/lib -lusb-1.0 -I/usr/local/include/boost -o diane -O2
debug:
	c++ main.cpp dinast_grabber.cpp -L/usr/local/lib -lusb-1.0 -I/usr/local/include/boost -o diane -g
