%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% UPenn THOR Human-Robot Interface
%% Copyright 2013 Stephen McGill
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function [] = setup_gui()
    warning off;
    global H_FIGURE;
    global CAMERA LIDAR BODY SLAM NETMON CONTROL HMAP DEBUGMON WAYPOINTS

    camera_sq_sz = .5;
    buffer = 0.01;

    FIRST_COL  = 0 + buffer/2;
    SECOND_COL = (1-camera_sq_sz)/2 + buffer/2;
    THIRD_COL  = 1-(1-camera_sq_sz)/2 + buffer/2;

    FIRST_ROW = 1-camera_sq_sz/2 + buffer/2;
    SECOND_ROW_CAM = 1-camera_sq_sz + buffer/2;
    THIRD_ROW_CAM = 0 + buffer/2;

    FIRST_COL_W = (1-camera_sq_sz)/2 - buffer;
    SECOND_COL_W = camera_sq_sz - buffer;
    THIRD_COL_W = (1-camera_sq_sz)/2 - buffer;

    FIRST_ROW_H = camera_sq_sz/2 - buffer;
    SECOND_ROW_H = camera_sq_sz/2 - buffer;
    THIRD_ROW_H = 1-camera_sq_sz - buffer;

    sz1 = 0.3;
    sz2 = 0.76;

    FIRST_ROW = 1-sz1 + buffer/2;
    SECOND_ROW = 1-sz2 + buffer/2;
    THIRD_ROW = 0 + buffer/2;

    FIRST_ROW_H = sz1 - buffer;
    SECOND_ROW_H = (sz2-sz1) - buffer;
    THIRD_ROW_H = 1-(sz2) - buffer;







    %% Setup the main figure
    f = figure(1);
    H_FIGURE = gcf;
    clf;
    set(H_FIGURE, 'Name', 'UPenn DRC monitor', ...
        'NumberTitle', 'off', ...
        'tag', 'Colortable', ...
        'MenuBar', 'none', ...
        'ToolBar', 'figure', ...
        'Color', [.05 .1 .05], ...
        'Colormap', gray(256), ...
        'position',[1 1 800 450], ...
        'doublebuffer','off' );

    % 	'KeyPressFcn',@KeyResponse);
    %'position',[1 1 1600 900], ...

    CONTROL = controlbody();
    WAYPOINTS = waypointbody();

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    H_MESH_AXES = axes('Parent', H_FIGURE, ...
        'XTick', [], 'YTick', [], 'Units', 'Normalized', ...
        'Position', [SECOND_COL+0.05 0.17 SECOND_COL_W-0.10 0.3]);

    H_DMAP_AXES = axes('Parent', H_FIGURE, ...
        'XTick', [], 'YTick', [], 'Units', 'Normalized', ...
        'Position', [THIRD_COL SECOND_ROW THIRD_COL_W SECOND_ROW_H]);

    % Robot visualization

    BODY = robotbody();
    BODY.init(H_MESH_AXES);

    rb1=uicontrol('Parent', H_FIGURE, 'Style', 'pushbutton', ...
        'String', 'View 1', 'Units', 'Normalized', ...
        'Position', [SECOND_COL SECOND_ROW_CAM-0.06 0.05 0.04] );

    rb2=uicontrol('Parent', H_FIGURE, 'Style', 'pushbutton', ...
        'String', 'View 2', 'Units', 'Normalized', ...
        'Position', [SECOND_COL SECOND_ROW_CAM-0.10 0.05 0.04] );

    rb3=uicontrol('Parent', H_FIGURE, 'Style', 'pushbutton', ...
        'String', 'View 3', 'Units', 'Normalized', ...
        'Position', [SECOND_COL SECOND_ROW_CAM-0.14 0.05 0.04] );

    rb4=uicontrol('Parent', H_FIGURE, 'Style', 'pushbutton', ...
        'String', 'View 4', 'Units', 'Normalized', ...
        'Position', [SECOND_COL SECOND_ROW_CAM-0.18 0.05 0.04] );

    set(rb1,'CallBack',{BODY.set_viewpoint,1});
    set(rb2,'CallBack',{BODY.set_viewpoint,2});
    set(rb3,'CallBack',{BODY.set_viewpoint,3});
    set(rb4,'CallBack',{BODY.set_viewpoint,4});


    % 3d mesh controls

    LIDAR = lidarbody();
    LIDAR.init(H_DMAP_AXES,H_MESH_AXES);

    lb1=uicontrol('Parent', H_FIGURE, 'Style', 'pushbutton', ...
        'String', 'Head LIDAR', 'Units', 'Normalized', ...
        'Position', [SECOND_COL SECOND_ROW_CAM-0.26 0.05 0.04] );

    lb2=uicontrol('Parent', H_FIGURE, 'Style', 'pushbutton', ...
        'String', 'Chest LIDAR', 'Units', 'Normalized', ...
        'Position', [SECOND_COL SECOND_ROW_CAM-0.30 0.05 0.04] );

    %depth map controls

    lmb1 = uicontrol('Parent', H_FIGURE, 'Style', 'pushbutton', ...
        'String', '+', 'Units', 'Normalized', ...
        'Position', [THIRD_COL+0.00 SECOND_ROW-0.05 0.02 0.04]);

    lmb2 = uicontrol('Parent', H_FIGURE, 'Style', 'pushbutton', ...
        'String', '-', 'Units', 'Normalized', ...
        'Position', [THIRD_COL+0.02 SECOND_ROW-0.05 0.02 0.04]);

    lmb3 = uicontrol('Parent', H_FIGURE, 'Style', 'pushbutton', ...
        'String', 'Clear', 'Units', 'Normalized', ...
        'FontSize', 14, ...
        'Position', [THIRD_COL+0.00 SECOND_ROW-0.09 0.04 0.04]);
    % switch head <-> chest
    lmb4 = uicontrol('Parent', H_FIGURE, 'Style', 'pushbutton', ...
        'String', 'Chest', 'Units', 'Normalized', ...
        'FontSize', 14, ...
        'Position', [THIRD_COL+0.00 SECOND_ROW-0.12 0.04 0.04]);
    lmb5 = uicontrol('Parent', H_FIGURE, 'Style', 'pushbutton', ...
        'String', 'Acquire', 'Units', 'Normalized', ...
        'FontSize', 14, ...
        'Position', [THIRD_COL+0.00 SECOND_ROW-0.15 0.04 0.04]);

    set(lb1,'CallBack',{LIDAR.set_meshtype,0});
    set(lb2,'CallBack',{LIDAR.set_meshtype,1});
    set(lmb1,'CallBack',{LIDAR.set_zoomlevel,1});
    set(lmb2,'CallBack',{LIDAR.set_zoomlevel,2});
    set(lmb3,'CallBack',{LIDAR.clear_points});
    set(lmb4,'CallBack',{LIDAR.set_img_display});
    set(lmb5,'CallBack',{LIDAR.get_depth_img});

    % Various calculations

    MODELS = models();

    lc1 = uicontrol('Parent', H_FIGURE, 'Style', 'pushbutton', ...
        'String', 'Wheel', 'Units', 'Normalized', ...
        'FontSize', 14, ...
        'Position', [THIRD_COL-0.05 SECOND_ROW_CAM-0.05 0.04 0.04]);
    lc2 = uicontrol('Parent', H_FIGURE, 'Style', 'pushbutton', ...
        'String', 'Door', 'Units', 'Normalized', ...
        'FontSize', 14, ...
        'Position', [THIRD_COL-0.05 SECOND_ROW_CAM-0.09 0.04 0.04]);
    lc3 = uicontrol('Parent', H_FIGURE, 'Style', 'pushbutton', ...
        'String', 'Tool', 'Units', 'Normalized', ...
        'FontSize', 14, ...
        'Position', [THIRD_COL-0.05 SECOND_ROW_CAM-0.13 0.04 0.04]);

    lc4 = uicontrol('Parent', H_FIGURE, 'Style', 'pushbutton', ...
        'String', 'Step', 'Units', 'Normalized', ...
        'FontSize', 14, ...
        'Position', [THIRD_COL-0.05 SECOND_ROW_CAM-0.17 0.04 0.04]);

    set(lc1,'CallBack',MODELS.wheel_calc);
    set(lc2,'CallBack',MODELS.door_calc);
    set(lc3,'CallBack',MODELS.tool_calc);
    set(lc4,'CallBack',MODELS.step_calc);

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
    % Head Camera
    
    HCAMERA_AXES = axes('Parent', H_FIGURE, ...
        'YDir', 'reverse','XTick', [],'YTick', [], 'Units', 'Normalized', ...
        'Position', [SECOND_COL SECOND_ROW_CAM SECOND_COL_W camera_sq_sz-buffer]);
    
    % Left hand camera
    
    LCAMERA_AXES = axes('Parent', H_FIGURE, ...
        'XTick', [], 'YTick', [], 'Units', 'Normalized', ...
        'Position', [FIRST_COL FIRST_ROW FIRST_COL_W FIRST_ROW_H]);
    
    % Right hand camera
    RCAMERA_AXES = axes('Parent', H_FIGURE, ...
        'XTick', [], 'YTick', [], 'Units', 'Normalized', ...
        'Position', [THIRD_COL FIRST_ROW THIRD_COL_W FIRST_ROW_H]);
    
    CAMERA = camerabody();
    CAMERA.init(HCAMERA_AXES,LCAMERA_AXES,RCAMERA_AXES);
    
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
    % SLAM image
    H_SLAM_AXES = axes('Parent', H_FIGURE, ...
        'XDir','reverse', 'XTick', [], 'YTick', [],'Units', 'Normalized', ...
        'Position', [FIRST_COL SECOND_ROW FIRST_COL_W SECOND_ROW_H]);
    
    SLAM  = slambody();
    SLAM.init( H_SLAM_AXES);
    
    sb1=uicontrol('Parent', H_FIGURE, 'Style', 'pushbutton', ...
        'String', '+', 'Units', 'Normalized', ...
        'Position', [SECOND_COL-0.05 SECOND_ROW-0.05 0.02 0.04]);
    
    sb2=uicontrol('Parent', H_FIGURE, 'Style', 'pushbutton', ...
        'String', '-', 'Units', 'Normalized', ...
        'Position', [SECOND_COL-0.03 SECOND_ROW-0.05 0.02 0.04]);
   
    sb3=uicontrol('Parent', H_FIGURE, 'Style', 'pushbutton', ...
        'String', 'Clear', 'Units', 'Normalized', ...
        'Position', [SECOND_COL-0.05 SECOND_ROW-0.09 0.04 0.04]);

    set(sb1,'CallBack',{SLAM.set_zoomlevel,1});
    set(sb2,'CallBack',{SLAM.set_zoomlevel,2});
    set(sb3,'CallBack',{WAYPOINTS.clear_waypoints});
    
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
    % Network Status monitor
    
    NETMON = netmonbody();

    H_NETWORK_AXES = axes('Parent', H_FIGURE, ...
        'XTick', [], 'YTick', [], 'Units', 'Normalized', ...
        'Position', [SECOND_COL-0.065 0.005 0.18 0.080]);
    
    H_NETWORK_TEXT = uicontrol('Style','text','Units','Normalized',...
        'Position', [SECOND_COL-0.065 0.085 0.18 0.02]);
    
    H_DEBUG_TEXT = uicontrol('Style','text','Units','Normalized',...
        'Position', [SECOND_COL-0.065+0.18 0.005 0.11 0.10]);
    
    
    NETMON.init(H_NETWORK_AXES,H_NETWORK_TEXT);
    
    
    
    DEBUGMON = debugbody();
    DEBUGMON.init(H_DEBUG_TEXT);
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %% Body FSM control
    %%
    b1=uicontrol('Parent', H_FIGURE, 'Style', 'pushbutton', ...
        'String', 'Init', ...
        'FontSize', 14, ...
        'Units', 'Normalized', ...
        'Position', [0.01 SECOND_ROW-0.06 0.09 0.06]);

    b4=uicontrol('Parent', H_FIGURE, 'Style', 'pushbutton', ...
        'String', 'Teleop', ...
        'FontSize', 14, ...
        'Units', 'Normalized', ...
        'Position', [0.10 SECOND_ROW-0.06 0.09 0.06] ...
        );

    b2=uicontrol('Parent', H_FIGURE, 'Style', 'pushbutton', ...
        'String', 'Approach', ...
        'FontSize', 14, ...
        'Units', 'Normalized', ...
        'Position', [0.01 SECOND_ROW-0.12 0.09 0.06] ...
        );

    b7=uicontrol('Parent', H_FIGURE, 'Style', 'pushbutton', ...
        'String', 'Stepover', ...
        'FontSize', 14, ...
        'Units', 'Normalized', ...
        'Position', [0.10 SECOND_ROW-0.12 0.09 0.06] ...
        );

    b3=uicontrol('Parent', H_FIGURE, 'Style', 'pushbutton', ...
        'String', 'Navigate', ...
        'FontSize', 14, ...
        'Units', 'Normalized', ...
        'Position', [0.01 SECOND_ROW-0.18 0.18 0.06] ...
        );
    b5=uicontrol('Parent', H_FIGURE, 'Style', 'pushbutton', ...
        'String', 'Sideways', ...
        'FontSize', 14, ...
        'Units', 'Normalized', ...
        'Position', [0.01 SECOND_ROW-0.24 0.09 0.06] ...
        );
    b6=uicontrol('Parent', H_FIGURE, 'Style', 'pushbutton', ...
        'String', 'Sideways Done', ...
        'FontSize', 14, ...
        'Units', 'Normalized', ...
        'Position', [0.10 SECOND_ROW-0.24 0.09 0.06] ...
        );

    set(b1,'CallBack',{CONTROL.body_control,'init'});   
    set(b2,'CallBack',{CONTROL.body_control,'approach'});
    set(b3,'CallBack',{CONTROL.body_control,'navigate'});
    set(b4,'CallBack',{CONTROL.body_control,'teleop'});
    set(b5,'CallBack',{CONTROL.body_control,'sideways'});
    set(b6,'CallBack',{CONTROL.body_control,'sidedone'});
    set(b7,'CallBack',{CONTROL.body_control,'stepover'});

    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %% Head FSM control
    %%
    
    h1=uicontrol('Parent', H_FIGURE, 'Style', 'pushbutton', ...
        'String', 'Head Fixed', ...
        'FontSize', 14, ...
        'Units', 'Normalized', ...
        'Position', [SECOND_COL+0.4 0.045 0.08 0.04]);
    
    h2=uicontrol('Parent', H_FIGURE, 'Style', 'pushbutton', ...
        'String', 'Head Center', ...
        'FontSize', 14, ...
        'Units', 'Normalized', ...
        'Position', [SECOND_COL+0.48 0.045 0.08 0.04]);
    
    h3=uicontrol('Parent', H_FIGURE, 'Style', 'pushbutton', ...
        'String', 'Regular scan', ...
        'FontSize', 14, ...
        'Units', 'Normalized', ...
        'Position', [SECOND_COL+0.4 0.005 0.08 0.04]);
    
    h4=uicontrol('Parent', H_FIGURE, 'Style', 'pushbutton', ...
        'String', 'Lower scan', ...
        'FontSize', 14, ...
        'Units', 'Normalized', ...
        'Position', [SECOND_COL+0.48 0.005 0.08 0.04]);
    
    set(h1,'CallBack',{CONTROL.head_control,'reset'});
    set(h2,'CallBack',{CONTROL.head_control,'center'});
    set(h3,'CallBack',{CONTROL.head_control,'tiltscan'});
    set(h4,'CallBack',{CONTROL.head_control,'stepscan'});
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %% Arm state machine control
    
    ARM_CONTROL_ROW = SECOND_ROW;
    a1=uicontrol('Parent', H_FIGURE, 'Style', 'pushbutton', ...
        'String', 'Init', ...
        'FontSize', 14, ...
        'Units', 'Normalized', ...
        'Position', [THIRD_COL+.05 ARM_CONTROL_ROW-0.06 0.05 0.06]);
    
    a2=uicontrol('Parent', H_FIGURE, 'Style', 'pushbutton', ...
        'String', 'Ready', ...
        'FontSize', 14, ...
        'Units', 'Normalized', ...
        'Position', [THIRD_COL+.1 ARM_CONTROL_ROW-0.06 0.05 0.06]);

    a3=uicontrol('Parent', H_FIGURE, 'Style', 'pushbutton', ...
        'String', 'Reset', ...
        'FontSize', 14, ...
        'Units', 'Normalized', ...
        'Position', [THIRD_COL+.15 ARM_CONTROL_ROW-0.06 0.05 0.06]);
    % grabbing
    a4=uicontrol('Parent', H_FIGURE, 'Style', 'pushbutton', ...
        'String', 'Grab', ...
        'FontSize', 14, ...
        'Units', 'Normalized', ...
        'Position', [THIRD_COL+.05 ARM_CONTROL_ROW-0.12 0.05 0.06]);
    a5=uicontrol('Parent', H_FIGURE, 'Style', 'pushbutton', ...
        'String', 'Teleop', ...
        'FontSize', 14, ...
        'Units', 'Normalized', ...
        'Position', [THIRD_COL+.1 ARM_CONTROL_ROW-0.12 0.05 0.06]);
    
        
    set(a1,'CallBack',{CONTROL.arm_control,'init'});
    set(a2,'CallBack',{CONTROL.arm_control,'ready'});
    set(a3,'CallBack',{CONTROL.arm_control,'reset'});
    set(a4,'CallBack',{CONTROL.arm_control,'grab'});
    set(a5,'CallBack',{CONTROL.arm_control,'teleop'});
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
end
