#!/bin/bash


# Kill all processes to reset player
killall -q naoqi-bin naoqi espeak lua luajit luajit2 screen MATLAB
#

# kill all screen log
rm -f screenlog*

SCREEN_FLAGS="-dm -L -S"

run_team_monitor(){
  echo "Starting listen_monitor"
  screen $SCREEN_FLAGS listenmonitor lua listen_monitor.lua
  sleep 1

  echo "Starting Monitor"
  cd ~/Desktop/UPennDev/Tools/Matlab
  screen $SCREEN_FLAGS monitor matlab -nojvm -nosplash -r Monitor
  # Allow Cognition some time to start
  sleep 1
}

case "$1" in
  '')
    echo "Start Monitor"
    run_monitor;
esac
