include ../../../Makefile.inc
MATLAB=matlab -nosplash -nodesktop
#MEX=mex -O $(INCLUDES)
MEX=mex -O -I/usr/local/include -L/usr/local/lib

%.o: %.cpp
	$(CXX) $(CXXFLAGS) $(INCLUDES) -o $@ -c $<
%.o: %.cc
	$(CXX) $(CXXFLAGS) $(INCLUDES) -o $@ -c $<
%.o: %.c
	$(CC) $(CFLAGS) $(INCLUDES) -o $@ -c $<