LIBNAME=slam
include ../../Makefile.inc
LIBOPTS+=-ltorch

# OpenMP
#LIBOPTS+=-fopenmp
#CXXFLAGS+=-fopenmp
#CFLAGS+=-fopenmp
#CC=gcc -std=c99
#CXX=g++
#LD=g++
#CC=OMP_NUM_THREADS=2 gcc
#CXX=OMP_NUM_THREADS=2 g++
#LD=OMP_NUM_THREADS=2 g++
