module(..., package.seeall)

-- this config file was automatically generated by the walk_tuner utility

walkOSC = {}

walkOSC.parameters = {
  a_offset = -0.000000,
  ankle_roll_fb = 0.140000,
  knee_pitch_fb = 0.020000,
  period_time = 1.600000,
  y_swing_amplitude = 0.050000,
  ankle_pitch_fb = -0.000000,
  hip_pitch_offset = -0.000300,
  hip_roll_fb = 0.010000,
  z_swing_amplitude = -0.000000,
  z_offset = -0.795900,
  y_offset = 0.102300,
  x_offset = 0.005400,
  step_amplitude = 0.030200,
  dsp_ratio = 0.300300,
  y_offset_ratio = 0.002000,
  zmp_shift_ratio = 0.400000,
  r_swing_amplitude = 0.001000,
}

walkOSC.increments = {
  a_offset = 0.001000,
  ankle_roll_fb = 0.001000,
  knee_pitch_fb = 0.001000,
  period_time = 0.001000,
  y_swing_amplitude = 0.001000,
  ankle_pitch_fb = 0.001000,
  hip_pitch_offset = 0.001000,
  hip_roll_fb = 0.001000,
  z_swing_amplitude = 0.001000,
  z_offset = 0.001000,
  y_offset = 0.001000,
  x_offset = 0.001000,
  step_amplitude = 0.001000,
  dsp_ratio = 0.001000,
  y_offset_ratio = 0.001000,
  zmp_shift_ratio = 0.001000,
  r_swing_amplitude = 0.001000,
}

