module(..., package.seeall)

-- this config file was automatically generated by the walk_tuner utility

walk_osc = {}

walk_osc.parameters = {
  a_offset = -0.000000,
  ankle_roll_fb = 0.150000,
  knee_pitch_fb = 0.025000,
  period_time = 1.600000,
  y_swing_amplitude = 0.050000,
  ankle_pitch_fb = 0.170000,
  ankle_pitch_fb_slope = 0.750000,
  hip_pitch_offset = -0.000000,
  ankle_roll_fb_slope = 0.200000,
  z_swing_amplitude = -0.000000,
  z_offset = -0.795900,
  y_offset = 0.102300,
  x_offset = -0.000000,
  hip_roll_fb = 0.010000,
  dsp_ratio = 0.300000,
  y_offset_ratio = 0.004000,
  step_amplitude = 0.026700,
  zmp_shift_ratio = 0.460000,
}

walk_osc.increments = {
  a_offset = 0.001000,
  ankle_roll_fb = 0.001000,
  knee_pitch_fb = 0.001000,
  period_time = 0.001000,
  y_swing_amplitude = 0.001000,
  ankle_pitch_fb = 0.001000,
  ankle_pitch_fb_slope = 0.001000,
  hip_pitch_offset = 0.001000,
  ankle_roll_fb_slope = 0.001000,
  z_swing_amplitude = 0.001000,
  z_offset = 0.001000,
  y_offset = 0.001000,
  x_offset = 0.001000,
  hip_roll_fb = 0.001000,
  dsp_ratio = 0.001000,
  y_offset_ratio = 0.001000,
  step_amplitude = 0.001000,
  zmp_shift_ratio = 0.001000,
}

