module(..., package.seeall)

-- this config file was automatically generated by the walk_tuner utility

walkOSC = {}

walkOSC.parameters = {
  x_shift_ratio = 0.500000,
  a_offset = -0.000000,
  ankle_pitch_fb = -0.000000,
  ankle_roll_fb = -0.000000,
  hip_pitch_offset = -0.000000,
  y_shift_ratio = 0.500000,
  z_swing_amplitude = 0.004000,
  z_offset = -0.795900,
  y_offset = 0.108900,
  x_offset = 0.035000,
  period_time = 1.340000,
  dsp_ratio = 0.280000,
  step_amplitude = 0.023000,
  y_swing_amplitude = 0.044000,
  r_swing_amplitude = 0.003000,
}

walkOSC.increments = {
  x_shift_ratio = 0.001000,
  a_offset = 0.001000,
  ankle_pitch_fb = 0.001000,
  ankle_roll_fb = 0.001000,
  hip_pitch_offset = 0.001000,
  y_shift_ratio = 0.001000,
  z_swing_amplitude = 0.001000,
  z_offset = 0.001000,
  y_offset = 0.001000,
  x_offset = 0.001000,
  period_time = 0.001000,
  dsp_ratio = 0.001000,
  step_amplitude = 0.001000,
  y_swing_amplitude = 0.001000,
  r_swing_amplitude = 0.001000,
}

