module(..., package.seeall)

-- this config file was automatically generated by the walk_tuner utility

walkOSC = {}

walkOSC.parameters = {
  y_offset = 0.100000,
  z_offset = -0.775000,
  x_offset = 0.025000,
  z_swing_amplitude = 0.005000,
  period_time = 0.610000,
  y_swing_amplitude = 0.013000,
  step_amplitude = 0.011000,
  dsp_ratio = 0.110000,
  x_swing_ratio = 0.000000,
  hip_pitch_offset = 0.000000,
}

walkOSC.increments = {
  y_offset = 0.001000,
  z_offset = 0.001000,
  x_offset = 0.001000,
  z_swing_amplitude = 0.001000,
  period_time = 0.001000,
  y_swing_amplitude = 0.001000,
  step_amplitude = 0.001000,
  dsp_ratio = 0.001000,
  x_swing_ratio = 0.001000,
  hip_pitch_offset = 0.001000,
}

