module(..., package.seeall)

-- this config file was automatically generated by the walk_tuner utility

walk_osc = {}

walk_osc.parameters = {
  y_offset = 0.100000,
  z_offset = -0.760000,
  x_offset = 0.031000,
  ankle_roll_fb_slope = 0.000000,
  knee_pitch_fb = -0.000000,
  ankle_pitch_fb = 0.080000,
  hip_roll_fb = 0.000000,
  ankle_roll_fb = 0.080000,
  period_time = 1.360000,
  ankle_pitch_fb_slope = 0.000000,
  a_offset = 0.000000,
  hip_pitch_offset = -0.000000,
  zmp_shift_ratio = 0.500000,
  dsp_ratio = 0.250000,
  y_offset_ratio = 0.300000,
  y_swing_amplitude = 0.048000,
  z_swing_amplitude = 0.002000,
  step_amplitude = 0.034000,
}

walk_osc.increments = {
  y_offset = 0.001000,
  z_offset = 0.001000,
  x_offset = 0.001000,
  ankle_roll_fb_slope = 0.001000,
  knee_pitch_fb = 0.001000,
  ankle_pitch_fb = 0.001000,
  hip_roll_fb = 0.001000,
  ankle_roll_fb = 0.001000,
  period_time = 0.001000,
  ankle_pitch_fb_slope = 0.001000,
  a_offset = 0.001000,
  hip_pitch_offset = 0.001000,
  zmp_shift_ratio = 0.001000,
  dsp_ratio = 0.001000,
  y_offset_ratio = 0.001000,
  y_swing_amplitude = 0.001000,
  z_swing_amplitude = 0.001000,
  step_amplitude = 0.001000,
}

