% Define the plane models 
% using surface normals (mean, var), position in 3D (mean,% var), etc.
Mground = struct('mu_normal',[0 0 1],...
                 'sig_normal',0.2,...
                 'mu_height',0,...
                 'sig_height',0.03,...
                 'mu_size',0);
             
Mwall = struct('mu_normal_z',0,...
               'sig_normal',0.2,...
               'mu_size',0);
           
Mtable = struct('mu_normal',[0 0 1],...
                'sig_normal',0.2,...
                'mu_height',0.8,...
                'sig_height',0.1,...
                'mu_size',0);
            
Mstepable = struct('mu_normal',[0 0 1],...
                  'sig_normal',0.3,...
                  'mu_size',0);
