#! /bin/sh

if [ $1 = 'guest' ]; then
  rm /etc/conf.d/net
  touch /etc/conf.d/net
  case "$2" in
  hook)
  echo 'modifying network scripts for hook'
  cat ~nao/UPennDev/Player/network_scripts/conf.d_guest_hook >> /etc/conf.d/net ;;
  ruffio)
  echo 'modifying network scripts for ruffio'
  cat ~nao/UPennDev/Player/network_scripts/conf.d_guest_ruffio >> /etc/conf.d/net ;;
  tink)
  echo 'modifying network scripts for tink'
  cat ~nao/UPennDev/Player/network_scripts/conf.d_guest_tink >> /etc/conf.d/net ;;
  ticktock)
  echo 'modifying network scripts for ticktock'
  cat ~nao/UPennDev/Player/network_scripts/conf.d_guest_ticktock >> /etc/conf.d/net ;;
  pockets)
  echo 'modifying network scripts for pockets'
  cat ~nao/UPennDev/Player/network_scripts/conf.d_guest_pockets >> /etc/conf.d/net ;;
  esac
  rm /etc/wpa_supplicant/wpa_supplicant.conf
  touch /etc/wpa_supplicant/wpa_supplicant.conf
  cat ~nao/UPennDev/Player/network_scripts/wpa_supplicant.conf_guest >> /etc/wpa_supplicant/wpa_supplicant.conf

elif [ $1 = 'robocup' ]; then 
  rm /etc/conf.d/net
  touch /etc/conf.d/net
  case "$2" in
  hook)
  echo 'modifying network scripts for hook'
  cat ~nao/UPennDev/Player/network_scripts/conf.d_robocup_hook >> /etc/conf.d/net ;;
  ruffio)
  echo 'modifying network scripts for ruffio'
  cat ~nao/UPennDev/Player/network_scripts/conf.d_robocup_ruffio >> /etc/conf.d/net ;;
  tink)
  echo 'modifying network scripts for tink'
  cat ~nao/UPennDev/Player/network_scripts/conf.d_robocup_tink >> /etc/conf.d/net ;;
  ticktock)
  echo 'modifying network scripts for ticktock'
  cat ~nao/UPennDev/Player/network_scripts/conf.d_robocup_ticktock >> /etc/conf.d/net ;;
  pockets)
  echo 'modifying network scripts for pockets'
  cat ~nao/UPennDev/Player/network_scripts/conf.d_robocup_pockets >> /etc/conf.d/net ;;
  esac
  rm /etc/wpa_supplicant/wpa_supplicant.conf
  touch /etc/wpa_supplicant/wpa_supplicant.conf
  cat ~nao/UPennDev/Player/network_scripts/wpa_supplicant.conf_robocup >> /etc/wpa_supplicant/wpa_supplicant.conf
 else
   echo 'invalid or unrecognized network :('
 fi
 echo '/etc/wpa_supplicant/wpa_supplicant.conf and /etc/conf.d/net written'
 echo 'now restarting network interface'
 /etc/init.d/net.wlan0 stop && /etc/init.d/net.wlan0 start
 /etc/init.d/sshd restart
echo 'done'
