#! /bin/bash

#LUA=lua
LUA=luajit

# webots_controller : launches lua scripts in webots
Webots_Home=/usr/local/webots

# For Mac systems!
COMPUTER=`uname`
if [ "$COMPUTER" = "Darwin" ]
then
	echo "On OSX!"
	eval `/usr/libexec/path_helper -s`
	source ~/.bash_profile
	Webots_Home=/Applications/Webots
else
	echo "On Linux!"
fi

# Setup dynamic library path
# ---------------------------------------------------------------------
export LD_LIBRARY_PATH=$Webots_Home/lib:$LD_LIBRARY_PATH

# Change to directory containing this file 
# ---------------------------------------------------------------------
RELATIVE_PATH=`echo $0 | sed 's/\(.*\)\/.*$/\1/'`
cd -P $RELATIVE_PATH

# Run lua script depending on controller arguments
# ---------------------------------------------------------------------
if [ "$1" = "motion_manager" ]
then
  echo Starting motion_manager...
  exec xterm -fn 9x15 -hold -e $LUA motion_manager.lua
elif [ "$1" = "keyframe_editor" ]
then
  echo Starting keyframe_editor...
  exec xterm -fn 9x15 -hold -e $LUA keyframe_editor.lua
elif [ "$1" = "bias_editor" ]
then
  echo Starting bias_editor...
  exec xterm -fn 9x15 -hold -e $LUA bias_editor.lua
elif [ "$1" = "test_webots" ]
then
  echo Starting test_webots
  cd Test/Util
  exec xterm -fn 9x15 -hold -e $LUA test_webots.lua
elif [ "$1" = "test_balance" ]
then
  echo Starting test_balance...
  cd Test/Motion
  exec $LUA test_balance.lua
elif [ "$1" = "test_swing" ]
then
  echo Starting test_swing...
  cd Test/Motion
  exec $LUA test_swing.lua
elif [ "$1" = "test_pid" ]
then
  echo Starting test_pid...
  cd Test/Motion
  exec $LUA test_pid.lua
elif [ "$1" = "test_id_stance" ]
then
  echo Starting test_id_stance
  cd Test/Motion
  exec $LUA test_id_stance.lua
elif [ "$1" = "test_walk" ]
then
  echo Starting test_walk...
  cd Test/Motion
  exec xterm -fn 9x15 -hold -e $LUA test_walk.lua 
elif [ "$1" = "test_robot_balance2" ]
then
  echo Starting test_robot_balance2...
  cd Test/Motion
  exec xterm -fn 9x15 -hold -e $LUA test_robot_balance2.lua 
elif [ "$1" = "balance" ]
then
  echo Starting balance...
  cd Test/Motion
  exec xterm -fn 9x15 -hold -e $LUA balance.lua 
elif [ "$1" = "find_cog" ]
then
  echo Starting find_cog...
  cd Test/Motion
  exec xterm -fn 9x15 -hold -e $LUA find_cog.lua 
elif [ "$1" = "goto_home" ]
then
  echo Starting goto_home...
  cd Test/Motion
  exec xterm -fn 9x15 -hold -e $LUA goto_home.lua 
elif [ "$1" = "walk_tuner" ]
then
  echo Starting walk_tuner...
  exec xterm -fn 9x15 -hold -e $LUA walk_tuner.lua
elif [ "$1" = "train_step_rmp" ]
then
  echo Starting train_step_rmp...
  cd Learn/step_rmp
  exec $LUA train_step_rmp.lua
elif [ "$1" = "test_step_rmp" ]
then
  echo Starting test_step_rmp...
  cd Learn/step_rmp
  exec $LUA test_step_rmp.lua
elif [ "$1" = "evaluate_step_rmp" ]
then
  echo Starting evaluate_step_rmp...
  cd Learn/step_rmp
  exec $LUA evaluate_step_rmp.lua
elif [ "$1" = "test_slam" ]
then
  echo Starting test_slam
  cd Test/Cognition
  exec xterm -geometry 80x40 -fn 9x15 -hold -e $LUA test_slam.lua
else 
  echo Starting motion_manager...
  exec xterm -fn 9x15 -hold -e $LUA motion_manager.lua
fi
