LIBNAME=mattorch
include ../../Makefile.inc
LDFLAGS+=-ltorch -lmat -lmx
INCLUDES+=-I"/Applications/MATLAB_R2015b.app/extern/include"
LDFLAGS+=-L/Applications/MATLAB_R2015b.app/bin/maci64 \
				 -rpath /Applications/MATLAB_R2015b.app/bin/maci64
