LIBNAME=openni
include ../../Makefile.inc
INCLUDES+=-I/usr/local/include/OpenNI2
LIBOPTS+=-lOpenNI2
ifdef USE_NITE_SKELETON
INCLUDES+=-I/usr/local/include/NiTE -DUSE_NITE_SKELETON
LIBOPTS+=-lNiTE2
endif
