#! /bin/bash

COMPUTER=`uname`
PLATFORM=gazebo_ash
export THOR_HOME=$(dirname `pwd`)

echo "On Linux!"
echo "Assume default gazebo installation"

if [ "$1" ]
then
  WORLD_FILE=$1
else
  WORLD_FILE="default"
fi
WORLD_FILE="$THOR_HOME/Platform/$PLATFORM/Worlds/$WORLD_FILE.world"
export GAZEBO_MODEL_PATH="$THOR_HOME/Platform/$PLATFORM/Models"
export GAZEBO_PLUGIN_PATH="$GAZEBO_PLUGIN_PATH:\
$THOR_HOME/Platform/Lib/Gazebo/gz_comms_manager:\
$THOR_HOME/Platform/Lib/Gazebo/gz_time_publisher:\
"
  
echo "Opening $WORLD_FILE"
exec gazebo $WORLD_FILE
